Recent searches feature
omnivore-app/omnivore pull request #1294
Opened 2022-10-10 09:45 UTC by sywhb

2022-10-10 10:03 UTC, sywhb commented
> Nice timing, just improving this on the client

Lol. Yeah, I saw that

2022-10-10 10:10 UTC, jacksonh requested changes

2022-10-10 10:10 UTC, jacksonh commented on packages/api/src/entity/search_history.ts
> +  keyword!: string
Can we make this "term" ?

2022-10-10 10:12 UTC, sywhb commented on packages/api/src/entity/search_history.ts
> +  keyword!: string
Yes 👍 that is more accurate

2022-10-12 05:36 UTC, sywhb commented
Hey @jacksonh this is ready for review

2022-10-12 05:36 UTC, sywhb commented on packages/api/src/entity/search_history.ts
> +  keyword!: string
Updated

2022-10-12 12:51 UTC, jacksonh approved these changes

2022-10-12 14:11 UTC, merged