iOS recommendation groups
omnivore-app/omnivore pull request #1510
Opened 2022-12-05 07:46 UTC by jacksonh

- Add rough UI for recommendation groups
- Remove unused view
- Remove unused import
- Basic page for accepting invites

2022-12-06 04:16 UTC, satindar commented on apple/OmnivoreKit/Sources/App/Views/Profile/RecommendationGroupView.swift
> +  @Published var networkError = true
Not sure if this is being used yet but should probably default to false

2022-12-07 03:02 UTC, sywhb requested changes

2022-12-07 03:03 UTC, jacksonh commented on packages/db/migrate.ts
> +reIndex().then(() => console.log('ran reindex'))
Ohhh yeah I didn't mean to commit any changes to this file, thanks. I was mostly experimenting in here.

2022-12-07 03:21 UTC, sywhb approved these changes

2022-12-07 06:16 UTC, jacksonh commented
I'm going to merge this one as-is so the backend changes can be deployed to demo and API made available, then create a new PR with some web + iOS fixes.

2022-12-07 06:16 UTC, merged