[WIP] Add Filters, and editing filters.
omnivore-app/omnivore pull request #2707
Opened 2023-08-30 17:38 UTC by Podginator

2023-08-31 01:29 UTC, jacksonh commented
man, this is fantastic. No idea how many people have asked for this.

2023-08-31 03:39 UTC, jacksonh commented
Looks like the one test failure is my fault, working on a fix, then we can rebase.

2023-08-31 07:31 UTC, Podginator commented on packages/db/migrations/0119.do.add_defaults_to_filters.sql
> +    ELSIF (TG_OP = 'INSERT' and NEW.position is null) THEN
Change to be defaultFilter is true rather than this.

2023-09-04 09:06 UTC, jacksonh commented
Going to check this one out again today. Works really well for me in testing.

2023-09-06 07:36 UTC, jacksonh commented on packages/db/migrations/0119.do.add_defaults_to_filters.sql
> +INSERT INTO omnivore.filters (user_id, category, name,  filter, position, default_filter)
Hey, so does this one do an insert for all users? I was thinking of handling that in the resolver just returning default values, but this is probably easier.

2023-09-06 07:39 UTC, jacksonh commented on packages/api/src/resolvers/filters/index.ts
> +      where: { id },
I think we should have user id here in the where clause too, otherwise users could "guess" uuids and query for other users filters I think.

2023-09-06 07:40 UTC, jacksonh commented on packages/api/src/services/create_user.ts
> +      await createDefaultFiltersForUser(t)(user.id)
I suppose this could also be done in postgres with a transaction

2023-09-06 07:40 UTC, jacksonh commented on packages/api/src/services/create_user.ts
> +      await createDefaultFiltersForUser(t)(user.id)
I mean trigger.

2023-09-06 07:41 UTC, jacksonh reviewed
Can we also add the "Oldest First" default filter `sort:saved-asc`

2023-09-06 07:44 UTC, jacksonh requested changes
Just had one comment on a query, and then hope we can add in `Oldest First` plus need to think about whether we should use a trigger to create new users filters.

2023-09-06 08:59 UTC, jacksonh commented on packages/api/src/services/create_user.ts
> +      await createDefaultFiltersForUser(t)(user.id)
OK, I don't really have a preference here. So I think this approach works. The one thing I'd say is it should probably be wrapped in a try/catch. I wouldn't want the user creation to fail.

2023-09-06 09:07 UTC, Podginator commented
Probably won't be able to make these changes until tomorrow, but on it 👍

2023-09-06 09:10 UTC, jacksonh commented on packages/db/migrations/0119.do.add_defaults_to_filters.sql
> +INSERT INTO omnivore.filters (user_id, category, name,  filter, position, default_filter)
I think your approach is right, its quite complex to handle the null case I think when you consider partially set default searches.

2023-09-07 09:26 UTC, jacksonh commented
Nice, going to deploy this to our staging environment and do some testing to see how quickly the filters load in the left menu. I've been thinking we could easily cache some of these items with SWR, like labels/filters/subscriptions which rarely change.

2023-09-07 09:27 UTC, merged