[OMN-189] : Settings View - Emails
omnivore-app/omnivore pull request #286
Opened 2022-03-22 02:15 UTC by gitstart-omnivore

## Spec Checklist
- [ ] Are Api endpoints ready and properly documented ?
- [x] Does the figma design fit the ticket description ?
- [x] Added video describing your plan of action ?

## Description

This is part of the base issue [Settings View](https://github.com/omnivore-app/omnivore/issues/193)

Omnivore allows users to create addresses that receive email and add it to a user's inbox. A user can create multiple email addresses. There is a temporary version of this page available at settings/emails.

![image](https://user-images.githubusercontent.com/31247452/157682973-8f43644b-3d44-4551-b650-a19fdcc7ece7.png)

A new design for this page has been created here:

https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=444%3A33319

Notes
The design for this view is slightly off. Visually it is correct, but the user experience is inaccurate. Email addresses are immutable. They can be created, and they can be deleted, but they can not be modified. Also, they are created by Omnivore's backend, so there should be no user input on this page.

The confirmation codes are created when a GMail address is linked with an Omnivore Inbox address. So in testing they will normally not be set.

[ ] List emails

[ ] Display confirmation code if set on an email

[ ] Create an email

[ ] Delete an email

[ ] Copy an email address

[ ] Copy a confirmation code

[ ] Light and dark mode support

[ ] Desktop and mobile support
## Loom
[loom video](https://www.loom.com/share/c70f859f86fd4e93af92da22e0f0a227)

## House Keeping
- [x] Added video describing your plan of action ?
- [x] Added Loom video ?
- [x] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [ ] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)

## How has this been tested?

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [x] Others

## Checklist:

- [x] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [ ] I have confirmed the payload for integrated API matches params on API docs
- [x] I have confirmed design matches Spec specified on Figma.

## Language translation

- [ ] Did you udpate/add a new text node ?
- [ ] I have updated language mapping JSOn in locale

## Remarks

- [ ] I added a new package to achieve this task.
- [ ] I have updated package.json

2022-03-22 04:11 UTC, jacksonh commented
Deploying this one to the demo environment.

2022-03-22 04:34 UTC, jacksonh commented
On mobile can we add padding above the table. Its a little too tight to the top of the page

Here's the designed version:

<img width="663" alt="Screen Shot 2022-03-21 at 21 32 59" src="https://user-images.githubusercontent.com/75189/159408758-5f6441ee-60df-4990-a500-2670645c29db.png">

and here is the actual:

<img width="412" alt="Screen Shot 2022-03-21 at 21 31 41" src="https://user-images.githubusercontent.com/75189/159408816-f64eff2c-9347-41da-b66a-14a5399a6ea6.png">

2022-03-22 04:36 UTC, jacksonh commented
On mobile because there is no header, we need to round the top corners of the first item. You can see in our version we have straight lines on the top row on mobile.

2022-03-22 04:40 UTC, jacksonh commented
On mobile can we add a little more padding to the two right side buttons. I know that will truncate the address but I think its a little too tight without. 

<img width="353" alt="Screen Shot 2022-03-21 at 21 39 32" src="https://user-images.githubusercontent.com/75189/159409358-5813a803-9a45-4863-aa23-2fea194d7284.png">

2022-03-22 04:42 UTC, jacksonh commented
On mobile the bottom button is too tight on the bottom of the page.

<img width="461" alt="Screen Shot 2022-03-21 at 21 42 17" src="https://user-images.githubusercontent.com/75189/159409598-47fc99c7-d752-4507-8061-9c1b1615e413.png">

2022-03-22 04:44 UTC, jacksonh commented on packages/web/components/elements/images/MoreOptionsIcon.tsx
> -  const dots =
Nice 👍

2022-03-22 04:44 UTC, jacksonh commented on packages/web/package.json
> +    "@radix-ui/react-tooltip": "^0.1.7",
👍

2022-03-22 04:44 UTC, jacksonh commented on packages/web/pages/_app.tsx
> +        <TooltipProvider delayDuration={200}>
Ah this is handy. Should be able to use these a lot more now.

2022-03-22 04:48 UTC, jacksonh commented
On desktop the `InfoIcon` should link to this page when tapped: https://omnivore.app/help/newsletters

2022-03-22 18:06 UTC, jacksonh requested changes
added some comments regarding visual issues, mostly on mobile

2022-03-22 22:10 UTC, gitstart-omnivore commented
@jacksonh we've effected the requested review changes, please take a look

2022-03-22 22:31 UTC, jacksonh commented
> @jacksonh we've effected the requested review changes, please take a look

Thanks, taking a look.

2022-03-22 22:37 UTC, jacksonh commented
Deploying this to the demo environment

2022-03-22 23:38 UTC, gitstart-omnivore commented
> This should just be the relative URL `/help/newsletters`

Fixed

2022-03-23 04:23 UTC, jacksonh commented
This looks good. I'll merge/deploy it in the morning.

2022-03-23 21:26 UTC, gitstart-omnivore commented
> There's one last small issue here. On mobile, if you have a single email, you don't get rounded corners, because this loop here doesn't account for the case where `i ===0` and `isLastChild` is true:
> 
> ```
>                   '@mdDown': {
>                     borderRadius: i === 0 ? '5px 5px 0 0 ' : '',
>                   },
>                   borderRadius: isLastChild ? '0 0 5px 5px' : '',
> ```

Fixed

2022-03-23 22:19 UTC, jacksonh commented
nice work.

2022-03-23 22:23 UTC, jacksonh approved these changes

2022-03-23 22:23 UTC, merged