Add an index to the subscriptions name column
omnivore-app/omnivore pull request #3492
Opened 2024-02-03 01:39 UTC by jacksonh

2024-02-05 08:28 UTC, sywhb requested changes

2024-02-05 08:28 UTC, sywhb commented on packages/db/migrations/0161.do.add_subscriptions_name_index.sql
> +CREATE INDEX CONCURRENTLY IF NOT EXISTS subscriptions_name_index ON omnivore.subscriptions (name);
i think the index should be on `user_id` and `name`

2024-02-05 13:49 UTC, jacksonh commented
Thanks agreed on adding user id. Here are the two where statements pganalyze found:

`WHERE ( ("Subscription"."name" = $1 AND "Subscription"."type" = $2 AND "Subscription__Subscription_user"."id" = $3) ) AND ( "Subscription"."id" IN ($0) )`

and

`WHERE ("Subscription"."name" = $1 AND "Subscription"."type" = $2 AND "Subscription__Subscription_user"."id" = $3)`

2024-02-06 05:11 UTC, sywhb approved these changes

2024-02-06 05:18 UTC, merged