OMN-506
omnivore-app/omnivore pull request #533
Opened 2022-05-03 17:24 UTC by gitstart-omnivore

## Spec Checklist
- [ ] Are Api endpoints ready and properly documented ?
- [x] Does the figma design fit the ticket description ?
- [x] Added video describing your plan of action ?

## Description

Save Links to read later: This page displays the installation component showing users how to install the app and browser extensions. Design: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=2059%3A59254

## House Keeping
- [ ] Added video describing your plan of action ?
- [x] Added Loom video ?
- [x] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [x] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)

[Task link](https://app.gitstart.com/tasks/55316)
[Loom Video](https://www.loom.com/share/cc7084d1d3354677ab588109fb5980bf)

## How has this been tested?

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Others

## Checklist:

- [x] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [ ] I have confirmed the payload for integrated API matches params on API docs
- [x] I have confirmed design matches Spec specified on Figma.

## Language translation

- [x] Did you udpate/add a new text node ?
- [ ] I have updated language mapping JSOn in locale

## Remarks

- [ ] I added a new package to achieve this task.
- [ ] I have updated package.json

2022-05-03 17:27 UTC, jacksonh commented
Can we also get a storybook for this one?

2022-05-03 17:47 UTC, gitstart-omnivore commented
Currently implements Page 02 of the onboarding pages.

We had some questions regarding the other pages.
For page one where do we get the article list to display, which API endpoint do we call? Also what happens when you user presses next.

For page three where do we get the newsletters and also what happens when the next button is pressed?

@jacksonh We will work on the storybook in the mean time.

2022-05-04 04:02 UTC, jacksonh commented on packages/web/components/elements/ExtensionsInstallHelp.tsx
> +          <img
Do we need this change? It will remove the high resolution image on higher density screens.

2022-05-04 04:04 UTC, jacksonh commented on packages/web/components/elements/ExtensionsInstallHelp.tsx
> +          <img
Ah I see. Its a new image, we need to update the high resolution version too.

2022-05-04 13:22 UTC, gitstart-omnivore commented
@jacksonh Do we add the entire page in the storybook or just the OnboardingLayout2 component.

2022-05-04 13:27 UTC, gitstart-omnivore commented on packages/web/pages/onboarding/02.tsx
> +          src='/static/images/onboarding/browser-extension.svg'
We had to use an .svg file here as well. Because the .png file would look blurry. Especially the text on it.

2022-05-04 16:03 UTC, jacksonh requested changes
Can we move more of `02.tsx` into a component and then create a storybook for it?

2022-05-04 20:55 UTC, gitstart-omnivore commented
Hi @jacksonh We have created a storybook for the page.

Also could you respond to my questions regarding the onboarding tasks, thanks!

> Currently implements Page 02 of the onboarding pages.
> 
> We had some questions regarding the other pages. For page one where do we get the article list to display, which API endpoint do we call? Also what happens when you user presses next.
> 
> For page three where do we get the newsletters and also what happens when the next button is pressed?
> 
> @jacksonh We will work on the storybook in the mean time.

2022-05-09 17:11 UTC, gitstart-omnivore commented
We have added Onboarding Page 3 and also created the story for it.

This PR now contains two pages, Page 2 and, Page 3.

2022-05-10 04:49 UTC, jacksonh approved these changes

2022-05-10 04:49 UTC, jacksonh commented
This looks great, thanks for the storybooks

2022-05-10 20:28 UTC, merged